# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppProject', '0005_auto_20170307_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='Comment', max_length=128),
        ),
    ]
