# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppProject', '0010_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
