# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppProject', '0024_auto_20170317_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='hey there', max_length=250),
        ),
    ]
