# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppProject', '0025_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
