# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppProject', '0026_remove_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.CharField(default='', max_length=128),
        ),
    ]
